


CREATE TABLE wb_id33732.dim_costprice (
	supplierarticle varchar(100) NULL,
	costprice numeric(7, 2) NULL,
	season varchar(50) NULL,
	effective_from timestamp(0) NULL,
	effective_to timestamp(0) NULL,
	deleted_flg int4 NULL
);



CREATE TABLE wb_id33732.fact_incomes (
	incomeid varchar(8) NULL,
	"number" varchar(8) NULL,
	"date" timestamp(0) NULL,
	lastchangedate timestamp(0) NULL,
	supplierarticle varchar(100) NULL,
	techsize varchar(10) NULL,
	barcode varchar(20) NULL,
	quantity int4 NULL,
	totalprice numeric(7) NULL,
	dateclose timestamp(0) NULL,
	warehousename varchar(50) NULL,
	nmid varchar(9) NULL,
	status varchar(10) NULL
);




CREATE TABLE wb_id33732.fact_orders (
	"date" timestamp(0) NULL,
	lastchangedate timestamp(0) NULL,
	supplierarticle varchar(100) NULL,
	techsize varchar(10) NULL,
	barcode varchar(20) NULL,
	totalprice numeric(7) NULL,
	discountpercent int4 NULL,
	warehousename varchar(30) NULL,
	oblast varchar(100) NULL,
	incomeid varchar(30) NULL,
	odid varchar(30) NULL,
	nmid varchar(30) NULL,
	subject varchar(30) NULL,
	category varchar(30) NULL,
	brand varchar(30) NULL,
	iscancel varchar(30) NULL,
	cancel_dt timestamp(0) NULL,
	gnumber varchar(30) NULL,
	sticker varchar(30) NULL,
	srid varchar(100) NULL
);



CREATE TABLE wb_id33732.fact_reportdetailbyperiod (
	realizationreport_id int4 NULL,
	date_from timestamp(0) NULL,
	date_to timestamp(0) NULL,
	create_dt timestamp(0) NULL,
	suppliercontract_code varchar(40) NULL,
	rrd_id varchar(20) NULL,
	gi_id varchar(16) NULL,
	subject_name varchar(40) NULL,
	nm_id varchar(40) NULL,
	brand_name varchar(40) NULL,
	sa_name varchar(100) NULL,
	ts_name varchar(16) NULL,
	barcode varchar(20) NULL,
	doc_type_name varchar(7) NULL,
	quantity int4 NULL,
	retail_price numeric(7, 2) NULL,
	retail_amount numeric(7, 2) NULL,
	sale_percent numeric(7, 2) NULL,
	commission_percent numeric(4, 2) NULL,
	office_name varchar(50) NULL,
	supplier_oper_name varchar(40) NULL,
	order_dt timestamp(0) NULL,
	sale_dt timestamp(0) NULL,
	rr_dt timestamp(0) NULL,
	shk_id varchar(50) NULL,
	retail_price_withdisc_rub numeric(7, 2) NULL,
	delivery_amount int4 NULL,
	return_amount int4 NULL,
	delivery_rub numeric(7, 2) NULL,
	gi_box_type_name varchar(40) NULL,
	product_discount_for_report int4 NULL,
	supplier_promo int4 NULL,
	rid varchar(40) NULL,
	ppvz_spp_prc numeric(7, 2) NULL,
	ppvz_kvw_prc_base numeric(7, 2) NULL,
	ppvz_kvw_prc numeric(7, 2) NULL,
	ppvz_sales_commission numeric(7, 2) NULL,
	ppvz_for_pay numeric(7, 2) NULL,
	ppvz_reward numeric(7, 2) NULL,
	acquiring_fee numeric(7, 2) NULL,
	acquiring_bank varchar(50) NULL,
	ppvz_vw numeric(7, 2) NULL,
	ppvz_vw_nds numeric(7, 2) NULL,
	ppvz_office_id varchar(12) NULL,
	ppvz_office_name varchar(22) NULL,
	ppvz_supplier_id varchar(10) NULL,
	ppvz_supplier_name varchar(100) NULL,
	ppvz_inn varchar(30) NULL,
	declaration_number varchar(10) NULL,
	sticker_id varchar(10) NULL,
	site_country varchar(2) NULL,
	penalty numeric(8, 2) NULL,
	additional_payment numeric(7, 2) NULL,
	srid varchar(100) NULL,
	kiz varchar(85) NULL,
	bonus_type_name varchar(100) NULL
);



CREATE TABLE wb_id33732.fact_sales (
	"date" timestamp(0) NULL,
	lastchangedate timestamp(0) NULL,
	supplierarticle varchar(100) NULL,
	techsize varchar(10) NULL,
	barcode varchar(20) NULL,
	totalprice numeric(7) NULL,
	discountpercent numeric(2) NULL,
	issupply varchar(5) NULL,
	isrealization varchar(10) NULL,
	promocodediscount int4 NULL,
	warehousename varchar(100) NULL,
	countryname varchar(40) NULL,
	oblastokrugname varchar(50) NULL,
	regionname varchar(50) NULL,
	incomeid varchar(8) NULL,
	saleid varchar(20) NULL,
	odid varchar(20) NULL,
	spp varchar(1) NULL,
	forpay numeric(7, 2) NULL,
	finishedprice numeric(7, 2) NULL,
	pricewithdisc numeric(7, 2) NULL,
	nmid varchar(9) NULL,
	subject varchar(40) NULL,
	category varchar(40) NULL,
	brand varchar(40) NULL,
	isstorno int4 NULL,
	gnumber varchar(50) NULL,
	sticker varchar(10) NULL,
	srid varchar(50) NULL
);


CREATE TABLE wb_id33732.fact_stocks (
	reportbydate timestamp(0) NULL,
	lastchangedate timestamp(0) NULL,
	supplierarticle varchar(100) NULL,
	techsize varchar(10) NULL,
	barcode varchar(20) NULL,
	quantity int4 NULL,
	issupply varchar(10) NULL,
	isrealization varchar(5) NULL,
	quantityfull int4 NULL,
	warehousename varchar(50) NULL,
	nmid varchar(9) NULL,
	subject varchar(40) NULL,
	category varchar(40) NULL,
	daysonsite int4 NULL,
	brand varchar(40) NULL,
	sccode varchar(50) NULL,
	price numeric(7) NULL,
	discount int4 NULL
);

CREATE TABLE wb_id33732.stg_costprice (
	supplierarticle varchar(100) NULL,
	costprice numeric(7, 2) NULL,
	season varchar(50) NULL,
	"date" timestamp(0) NULL
);


CREATE TABLE wb_id33732.stg_incomes (
	incomeid varchar(8) NULL,
	"number" varchar(8) NULL,
	"date" timestamp(0) NULL,
	lastchangedate timestamp(0) NULL,
	supplierarticle varchar(100) NULL,
	techsize varchar(10) NULL,
	barcode varchar(20) NULL,
	quantity int4 NULL,
	totalprice numeric(7) NULL,
	dateclose timestamp(0) NULL,
	warehousename varchar(50) NULL,
	nmid varchar(9) NULL,
	status varchar(10) NULL
);


CREATE TABLE wb_id33732.stg_orders (
	"date" timestamp(0) NULL,
	lastchangedate timestamp(0) NULL,
	supplierarticle varchar(100) NULL,
	techsize varchar(10) NULL,
	barcode varchar(20) NULL,
	totalprice numeric(7) NULL,
	discountpercent int4 NULL,
	warehousename varchar(30) NULL,
	oblast varchar(100) NULL,
	incomeid varchar(30) NULL,
	odid varchar(30) NULL,
	nmid varchar(30) NULL,
	subject varchar(30) NULL,
	category varchar(30) NULL,
	brand varchar(30) NULL,
	iscancel varchar(30) NULL,
	cancel_dt timestamp(0) NULL,
	gnumber varchar(30) NULL,
	sticker varchar(30) NULL,
	srid varchar(100) NULL
);



CREATE TABLE wb_id33732.stg_reportdetailbyperiod (
	realizationreport_id int4 NULL,
	date_from timestamp(0) NULL,
	date_to timestamp(0) NULL,
	create_dt timestamp(0) NULL,
	suppliercontract_code varchar(40) NULL,
	rrd_id varchar(20) NULL,
	gi_id varchar(16) NULL,
	subject_name varchar(40) NULL,
	nm_id varchar(40) NULL,
	brand_name varchar(40) NULL,
	sa_name varchar(100) NULL,
	ts_name varchar(16) NULL,
	barcode varchar(20) NULL,
	doc_type_name varchar(7) NULL,
	quantity int4 NULL,
	retail_price numeric(7, 2) NULL,
	retail_amount numeric(7, 2) NULL,
	sale_percent numeric(7, 2) NULL,
	commission_percent numeric(4, 2) NULL,
	office_name varchar(50) NULL,
	supplier_oper_name varchar(40) NULL,
	order_dt timestamp(0) NULL,
	sale_dt timestamp(0) NULL,
	rr_dt timestamp(0) NULL,
	shk_id varchar(50) NULL,
	retail_price_withdisc_rub numeric(7, 2) NULL,
	delivery_amount int4 NULL,
	return_amount int4 NULL,
	delivery_rub numeric(7, 2) NULL,
	gi_box_type_name varchar(40) NULL,
	product_discount_for_report int4 NULL,
	supplier_promo int4 NULL,
	rid varchar(40) NULL,
	ppvz_spp_prc numeric(7, 2) NULL,
	ppvz_kvw_prc_base numeric(7, 2) NULL,
	ppvz_kvw_prc numeric(7, 2) NULL,
	ppvz_sales_commission numeric(7, 2) NULL,
	ppvz_for_pay numeric(7, 2) NULL,
	ppvz_reward numeric(7, 2) NULL,
	acquiring_fee numeric(7, 2) NULL,
	acquiring_bank varchar(50) NULL,
	ppvz_vw numeric(7, 2) NULL,
	ppvz_vw_nds numeric(7, 2) NULL,
	ppvz_office_id varchar(12) NULL,
	ppvz_office_name varchar(22) NULL,
	ppvz_supplier_id varchar(10) NULL,
	ppvz_supplier_name varchar(100) NULL,
	ppvz_inn varchar(30) NULL,
	declaration_number varchar(10) NULL,
	sticker_id varchar(10) NULL,
	site_country varchar(2) NULL,
	penalty numeric(8, 2) NULL,
	additional_payment numeric(7, 2) NULL,
	srid varchar(100) NULL,
	kiz varchar(85) NULL,
	bonus_type_name varchar(100) NULL
);


CREATE TABLE wb_id33732.stg_sales (
	"date" timestamp(0) NULL,
	lastchangedate timestamp(0) NULL,
	supplierarticle varchar(100) NULL,
	techsize varchar(10) NULL,
	barcode varchar(20) NULL,
	totalprice numeric(7) NULL,
	discountpercent numeric(2) NULL,
	issupply varchar(5) NULL,
	isrealization varchar(10) NULL,
	promocodediscount int4 NULL,
	warehousename varchar(100) NULL,
	countryname varchar(40) NULL,
	oblastokrugname varchar(50) NULL,
	regionname varchar(50) NULL,
	incomeid varchar(8) NULL,
	saleid varchar(20) NULL,
	odid varchar(20) NULL,
	spp varchar(1) NULL,
	forpay numeric(7, 2) NULL,
	finishedprice numeric(7, 2) NULL,
	pricewithdisc numeric(7, 2) NULL,
	nmid varchar(9) NULL,
	subject varchar(40) NULL,
	category varchar(40) NULL,
	brand varchar(40) NULL,
	isstorno int4 NULL,
	gnumber varchar(50) NULL,
	sticker varchar(10) NULL,
	srid varchar(50) NULL
);

CREATE TABLE wb_id33732.stg_stocks (
	lastchangedate timestamp(0) NULL,
	supplierarticle varchar(100) NULL,
	techsize varchar(10) NULL,
	barcode varchar(20) NULL,
	quantity int4 NULL,
	issupply varchar(10) NULL,
	isrealization varchar(5) NULL,
	quantityfull int4 NULL,
	warehousename varchar(50) NULL,
	nmid varchar(9) NULL,
	subject varchar(40) NULL,
	category varchar(40) NULL,
	daysonsite int4 NULL,
	brand varchar(40) NULL,
	sccode varchar(50) NULL,
	price numeric(7) NULL,
	discount int4 NULL
);